Repository radashi-org/radashi, pull requests merged in 2024-09, with the labels that each got.

#220 chore: use `radashi-helper`
  .devcontainer/devcontainer.json
  .vscode/extensions.json
  package.json
  pnpm-lock.yaml
Labels: maintenance

#237 ci: config renovate config file
  renovate.json
  scripts/format/format.ts
Labels: priority: high

#240 chore: make merge function work faster with large arrays
  benchmarks/array/merge.bench.ts
  src/array/merge.ts
Labels: 🔥 performance
