Repository radashi-org/radashi, pull requests merged in 2024-11, with the labels that each got.

#247 docs: fix runtime errors in docs examples for playground
  docs/array/list.mdx
  docs/async/defer.mdx
  docs/async/guard.mdx
  docs/async/map.mdx
  docs/async/reduce.mdx
  docs/async/retry.mdx
  docs/async/tryit.mdx
  docs/async/withResolvers.mdx
  docs/curry/debounce.mdx
  docs/curry/once.mdx
  docs/curry/throttle.mdx
  docs/function/castComparator.mdx
  docs/number/clamp.mdx
  docs/typed/isResultErr.mdx
  docs/typed/isResultOk.mdx
Labels: documentation, priority: high

#251 chore: add v12.2.0 release notes
  v12.2.0.md
Labels: documentation

#219 fix(types): improve `isEmpty` signature
  docs/typed/isEmpty.mdx
  src/typed/isEmpty.ts
  tests/typed/isEmpty.test-d.ts
  tests/typed/isEmpty.test.ts
Labels: better types

#160 fix(types): narrow return type of `first` and `last`
  src/array/first.ts
  src/array/last.ts
  tests/array/first.test-d.ts
  tests/array/last.test-d.ts
Labels: better types

#153 fix(types): improve `draw` signature for non-empty arrays
  src/random/draw.ts
  tests/random/draw.test-d.ts
Labels: better types

#262 feat: add `signal` option to `retry` and `parallel`
  .github/next-minor.md
  docs/async/parallel.mdx
  docs/async/retry.mdx
  src/async/parallel.ts
  src/async/retry.ts
  tests/async/parallel.test.ts
  tests/async/retry.test.ts
Labels: new feature, prerelease

#239 feat: add `isClass` function
  .github/next-minor.md
  benchmarks/typed/isClass.bench.ts
  docs/typed/isClass.mdx
  scripts/benchmarks/package.json
  scripts/common/package.json
  scripts/package.json
  scripts/radashi-db/package.json
  src/async/retry.ts
  src/mod.ts
  src/typed/isClass.ts
  src/types.ts
  tests/typed/isClass.test-d.ts
  tests/typed/isClass.test.ts
Labels: new feature, prerelease

#319 chore(renovate): be more conservative with dependency upgrades
  renovate.json
Labels: maintenance
