Repository radashi-org/radashi, pull requests merged in 2024-07, with the labels that each got.

#63 perf(cluster): avoid an array allocation
  src/array/cluster.ts
Labels: 🔥 performance

#58 feat: add `mapify` function
  benchmarks/array/mapify.bench.ts
  docs/array/mapify.mdx
  src/array/mapify.ts
  src/mod.ts
  tests/array/mapify.test.ts
Labels: new feature

#64 feat: add `unzip` function
  benchmarks/array/unzip.bench.ts
  docs/array/unzip.mdx
  src/array/unzip.ts
  src/array/zip.ts
  src/mod.ts
  tests/array/unzip.test.ts
Labels: new feature

#61 perf(replace): avoid creating 2 intermediate arrays
  src/array/replace.ts
Labels: 🔥 performance

#60 perf(merge): avoid arrow function in loop and avoid calling user-provided key generator more than once per item
  src/array/merge.ts
Labels: 🔥 performance

#62 perf(replaceOrAppend): avoid creating 2 intermediate arrays
  0001-feat-array-support-iterables-in-some-array-functions.patch
  src/array/replaceOrAppend.ts
Labels: 🔥 performance

#69 test: use fake timers in tests
  tests/async/parallel.test.ts
  tests/async/retry.test.ts
  tests/async/sleep.test.ts
  tests/curry/debounce.test.ts
  tests/curry/memo.test.ts
  tests/curry/throttle.test.ts
Labels: upstream fix, maintenance

#35 feat: add `flip` function
  docs/curry/flip.mdx
  src/curry/flip.ts
  src/mod.ts
  tests/curry/flip.test-d.ts
  tests/curry/flip.test.ts
Labels: new feature

#30 feat(pick): accept a callback for advanced picking
  docs/object/pick.mdx
  src/object/pick.ts
  tests/object/pick.test.ts
Labels: new feature

#59 feat: add `traverse` function
  benchmarks/object/traverse.bench.ts
  docs/object/traverse.mdx
  src/mod.ts
  src/object/traverse.ts
  src/typed/isIterable.ts
  tests/object/traverse.test.ts
Labels: new feature

#43 feat: add `castMapping` function
  docs/casted/castMapping.mdx
  src/casted/castMapping.ts
  src/mod.ts
  src/types.ts
  tests/casted/castMapping.test-d.ts
  tests/casted/castMapping.test.ts
Labels: new feature

#106 feat: add `clamp` function
  benchmarks/number/clamp.bench.ts
  docs/number/clamp.mdx
  src/mod.ts
  src/number/clamp.ts
  tests/number/clamp.test.ts
Labels: new feature

#97 feat: add `castArray` and `castArrayIfExists`
  benchmarks/casted/castArray.bench.ts
  benchmarks/casted/castArrayIfExists.bench.ts
  docs/casted/castArray.mdx
  docs/casted/castArrayIfExists.mdx
  src/casted/castArray.ts
  src/casted/castArrayIfExists.ts
  src/mod.ts
  tests/casted/castArray.test-d.ts
  tests/casted/castArray.test.ts
  tests/casted/castArrayIfExists.test-d.ts
  tests/casted/castArrayIfExists.test.ts
Labels: new feature

#34 feat: add `castComparator` function
  docs/casted/castComparator.mdx
  src/casted/castComparator.ts
  src/casted/castMapping.ts
  src/mod.ts
  src/types.ts
  tests/casted/castComparator.test-d.ts
  tests/casted/castComparator.test.ts
Labels: new feature

#100 feat(mapify): provide an index argument to the callbacks
  docs/array/mapify.mdx
  src/array/mapify.ts
  tests/array/mapify.test.ts
Labels: new feature

#96 chore: upgrade to vitest v2
  package.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: help wanted

#127 feat(throttle): add `trailing` option
  docs/curry/throttle.mdx
  src/curry/throttle.ts
  tests/curry/throttle.test.ts
Labels: new feature
