Repository radashi-org/radashi, pull requests merged in 2025-03, with the labels that each got.

#344 feat: add `remove` function
  benchmarks/array/remove.bench.ts
  docs/array/remove.mdx
  src/array/remove.ts
  src/mod.ts
  tests/array/remove.test.ts
Labels: new feature

#353 feat: add memoLastCall function
  .github/next-minor.md
  docs/curry/memoLastCall.mdx
  src/curry/memoLastCall.ts
  src/mod.ts
  tests/curry/memoLastCall.test.ts
Labels: new feature

#377 fix(counting)!: wrap return type with Partial
  src/array/counting.ts
Labels: BREAKING CHANGE, better types

#351 feat!: `trim` now requires both arguments
  docs/string/trim.mdx
  src/string/trim.ts
  tests/string/trim.test.ts
Labels: BREAKING CHANGE

#352 feat!: remove default size from `cluster`
  .github/next-major.md
  benchmarks/array/cluster.bench.ts
  docs/array/cluster.mdx
  src/array/cluster.ts
  tests/array/cluster.test.ts
Labels: BREAKING CHANGE
